local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TestEZ = require(ReplicatedStorage.DevPackages.TestEZ)
local StarterPlayerScripts = game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts")
local testsFolder = StarterPlayerScripts:WaitForChild("tests")
TestEZ.TestBootstrap:run({ testsFolder })
