local RankConfig = require(script.Parent.Parent.modules.gameData.RankConfig)

return function()
    describe("RankConfig.getRankForPoints", function()
        it("returns correct rank for points", function()
            local rank = RankConfig.getRankForPoints(10)
            expect(rank.name).to.equal("Beginner")
            rank = RankConfig.getRankForPoints(500)
            expect(rank.name).to.equal("Creative Pro")
            rank = RankConfig.getRankForPoints(2000)
            expect(rank.name).to.equal("Art Grandmaster")
            rank = RankConfig.getRankForPoints(3000)
            expect(rank.name).to.equal("Legendary Creator")
            rank = RankConfig.getRankForPoints(-5)
            expect(rank).to.equal(nil)
        end)
    end)

    describe("RankConfig.getRankByIndex", function()
        it("returns correct rank by index", function()
            local rank = RankConfig.getRankByIndex(1)
            expect(rank.name).to.equal("Beginner")
            rank = RankConfig.getRankByIndex(10)
            expect(rank.name).to.equal("Legendary Creator")
            rank = RankConfig.getRankByIndex(0)
            expect(rank).to.equal(nil)
        end)
    end)

    describe("RankConfig.getRankIndexForPoints", function()
        it("returns correct index for points", function()
            expect(RankConfig.getRankIndexForPoints(0)).to.equal(1)
            expect(RankConfig.getRankIndexForPoints(500)).to.equal(5)
            expect(RankConfig.getRankIndexForPoints(3000)).to.equal(10)
            expect(RankConfig.getRankIndexForPoints(-5)).to.equal(nil)
        end)
    end)
end
